#!/usr/bin/env python3
"""Train baseline plant-stimulus classifiers from the feature dataset."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
from typing import Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    make_scorer,
    precision_score,
    recall_score,
)
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


FEATURE_NAMES = [
    "mean",
    "std",
    "min",
    "max",
    "range",
    "median",
    "rms",
    "energy",
    "skewness",
    "kurtosis",
    "zero_crossing_rate",
    "slope",
    "q25",
    "q75",
    "iqr",
]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train baseline classifiers for plant-signal windows.")
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=Path("data/processed/feature_dataset.csv"),
        help="Feature dataset generated by create_dataset.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results"),
        help="Folder for metrics and confusion matrices. Default: results.",
    )
    parser.add_argument("--cv-folds", type=int, default=10, help="Requested cross-validation folds. Default: 10.")
    parser.add_argument("--random-state", type=int, default=42, help="Random seed. Default: 42.")
    return parser.parse_args(argv)


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.cv_folds < 2:
        raise SystemExit("--cv-folds must be at least 2.")
    if not args.input_csv.is_file():
        raise SystemExit(f"Feature dataset does not exist: {args.input_csv}")

    frame = pd.read_csv(args.input_csv)
    missing = set(FEATURE_NAMES + ["label"]) - set(frame.columns)
    if missing:
        raise SystemExit(f"Feature dataset is missing required columns: {sorted(missing)}")
    if frame.empty:
        raise SystemExit("Feature dataset is empty.")

    X = frame[FEATURE_NAMES]
    y = frame["label"].astype(str)
    class_counts = y.value_counts()
    if class_counts.size < 2:
        raise SystemExit("Training requires at least two classes.")
    if int(class_counts.min()) < 2:
        raise SystemExit("Each class needs at least two windows for a stratified train-test split.")

    try:
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.30,
            random_state=args.random_state,
            stratify=y,
        )
    except ValueError as exc:
        raise SystemExit(f"Could not create a stratified 70/30 split: {exc}") from exc

    cv_folds = min(args.cv_folds, int(class_counts.min()))
    if cv_folds < args.cv_folds:
        print(
            f"WARNING: requested {args.cv_folds}-fold CV but the smallest class has "
            f"{int(class_counts.min())} windows; using {cv_folds} folds.",
            file=sys.stderr,
        )

    minimum_training_size = min(len(X_train), len(X) - (len(X) // cv_folds))
    knn_neighbors = max(1, min(5, minimum_training_size))
    models = {
        "Random Forest": Pipeline(
            [
                ("imputer", SimpleImputer(strategy="median")),
                (
                    "classifier",
                    RandomForestClassifier(
                        n_estimators=300,
                        random_state=args.random_state,
                        class_weight="balanced",
                        n_jobs=-1,
                    ),
                ),
            ]
        ),
        "Extra Trees": Pipeline(
            [
                ("imputer", SimpleImputer(strategy="median")),
                (
                    "classifier",
                    ExtraTreesClassifier(
                        n_estimators=300,
                        random_state=args.random_state,
                        class_weight="balanced",
                        n_jobs=-1,
                    ),
                ),
            ]
        ),
        "KNN": Pipeline(
            [
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("classifier", KNeighborsClassifier(n_neighbors=knn_neighbors)),
            ]
        ),
    }
    scoring = {
        "accuracy": make_scorer(accuracy_score),
        "precision_macro": make_scorer(precision_score, average="macro", zero_division=0),
        "recall_macro": make_scorer(recall_score, average="macro", zero_division=0),
        "f1_macro": make_scorer(f1_score, average="macro", zero_division=0),
    }
    splitter = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=args.random_state)
    labels = sorted(y.unique())
    args.output_dir.mkdir(parents=True, exist_ok=True)
    metrics_rows: list[dict[str, float | int | str]] = []

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        # Run folds sequentially to avoid nested joblib process pools. The tree
        # estimators still parallelize their own fitting work with n_jobs=-1.
        cv_results = cross_validate(model, X, y, cv=splitter, scoring=scoring, n_jobs=1)

        metrics_row: dict[str, float | int | str] = {
            "model": model_name,
            "test_accuracy": accuracy_score(y_test, predictions),
            "test_precision_macro": precision_score(y_test, predictions, average="macro", zero_division=0),
            "test_recall_macro": recall_score(y_test, predictions, average="macro", zero_division=0),
            "test_f1_macro": f1_score(y_test, predictions, average="macro", zero_division=0),
            "cv_folds_used": cv_folds,
            "cv_accuracy_mean": cv_results["test_accuracy"].mean(),
            "cv_accuracy_std": cv_results["test_accuracy"].std(),
            "cv_precision_macro_mean": cv_results["test_precision_macro"].mean(),
            "cv_recall_macro_mean": cv_results["test_recall_macro"].mean(),
            "cv_f1_macro_mean": cv_results["test_f1_macro"].mean(),
        }
        metrics_rows.append(metrics_row)

        model_slug = slugify(model_name)
        report = pd.DataFrame(
            classification_report(y_test, predictions, labels=labels, output_dict=True, zero_division=0)
        ).transpose()
        report.to_csv(args.output_dir / f"classification_report_{model_slug}.csv")

        matrix = confusion_matrix(y_test, predictions, labels=labels)
        display = ConfusionMatrixDisplay(confusion_matrix=matrix, display_labels=labels)
        display.plot(cmap="Blues", xticks_rotation=45)
        plt.title(f"{model_name} confusion matrix")
        plt.tight_layout()
        plt.savefig(args.output_dir / f"confusion_matrix_{model_slug}.png", dpi=160)
        plt.close()

    metrics = pd.DataFrame(metrics_rows)
    metrics_path = args.output_dir / "results_metrics.csv"
    metrics.to_csv(metrics_path, index=False)

    with pd.option_context("display.max_columns", None, "display.width", 180):
        print(metrics.to_string(index=False))
    print(f"\nSaved metrics and confusion matrices to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
